spring:
  application:
    name: service-one

server:
  port: 9090

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST}

#eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/,${ADDITIONAL_EUREKA_SERVER_LIST}
#development - 9c67182964b29ee8e3d90e555830464e7bb0e2bc024926c3e35bfd171e7f4240
app:
  environmentname: '{cipher}9c67182964b29ee8e3d90e555830464e7bb0e2bc024926c3e35bfd171e7f4240'